# Generated by Django 3.2.8 on 2021-10-13 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_dict', models.JSONField()),
                ('termination_condition', models.JSONField()),
                ('date', models.DateField()),
                ('host_pc', models.CharField(max_length=255)),
                ('total_seconds', models.IntegerField()),
                ('witness_path', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Discovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=63)),
                ('absblock', models.JSONField()),
                ('num_insns', models.IntegerField()),
                ('witness_len', models.IntegerField()),
                ('interestingness', models.FloatField()),
                ('ab_coverage', models.FloatField()),
                ('generality', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InsnScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discovery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basic_ui.discovery')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interestingness', models.FloatField()),
                ('discovery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_ui.discovery')),
            ],
        ),
        migrations.CreateModel(
            name='DiscoveryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_index', models.IntegerField()),
                ('num_sampled', models.IntegerField()),
                ('num_interesting', models.IntegerField()),
                ('batch_time', models.IntegerField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_ui.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='discovery',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_ui.discoverybatch'),
        ),
        migrations.AddField(
            model_name='discovery',
            name='occurring_insnschemes',
            field=models.ManyToManyField(to='basic_ui.InsnScheme'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tools',
            field=models.ManyToManyField(to='basic_ui.Tool'),
        ),
        migrations.AddIndex(
            model_name='discoverybatch',
            index=models.Index(fields=['batch_index', 'campaign'], name='basic_ui_di_batch_i_95a43f_idx'),
        ),
    ]
