# Generated by Django 3.2.8 on 2021-10-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovery',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
