# Generated by Django 3.2.8 on 2021-10-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_ui', '0002_discovery_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovery',
            name='subsumed_by',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='discovery',
            name='ab_coverage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='discovery',
            name='interestingness',
            field=models.FloatField(null=True),
        ),
    ]
