# Generated by Django 3.2.8 on 2021-11-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_ui', '0003_auto_20211019_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='restrict_to_supported_insns',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
