# Generated by Django 4.0 on 2021-12-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_ui', '0004_campaign_restrict_to_supported_insns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discovery',
            name='ab_coverage',
        ),
    ]
