# Generated by Django 4.0.2 on 2022-03-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_ui', '0006_campaign_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absblock', models.JSONField()),
                ('witness_file', models.CharField(max_length=2048)),
                ('witness_len', models.IntegerField()),
                ('interestingness', models.FloatField(null=True)),
                ('generality', models.IntegerField()),
                ('remarks', models.TextField(null=True)),
                ('tools', models.ManyToManyField(to='basic_ui.Tool')),
            ],
        ),
    ]
