# Generated by Django 4.0.2 on 2022-06-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_ui', '0007_generalization'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalization',
            name='identifier',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='generalization',
            name='num_insns',
            field=models.IntegerField(default=42),
            preserve_default=False,
        ),
    ]
