# Generated by Django 4.0.2 on 2022-06-22 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_ui', '0008_generalization_identifier_generalization_num_insns'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicBlockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asm_str', models.TextField()),
                ('hex_str', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BasicBlockSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DiscoveryRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('bbentry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_ui.basicblockentry')),
                ('discovery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_ui.discovery')),
            ],
        ),
        migrations.CreateModel(
            name='BasicBlockMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField()),
                ('bb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_ui.basicblockentry')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_ui.tool')),
            ],
        ),
        migrations.AddField(
            model_name='basicblockentry',
            name='bbset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_ui.basicblockset'),
        ),
        migrations.AddField(
            model_name='basicblockentry',
            name='covered_by',
            field=models.ManyToManyField(related_name='covered_bbs', to='basic_ui.Discovery'),
        ),
        migrations.AddField(
            model_name='basicblockentry',
            name='interesting_for',
            field=models.ManyToManyField(related_name='interesting_bbs', to='basic_ui.Campaign'),
        ),
    ]
