# Generated by Django 4.0.2 on 2022-06-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_ui', '0009_basicblockentry_basicblockset_discoveryranking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicblockset',
            name='isa',
            field=models.CharField(default='x86', max_length=256),
            preserve_default=False,
        ),
    ]
