# Generated by Django 4.0.2 on 2022-06-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_ui', '0010_basicblockset_isa'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicblockset',
            name='has_data_for',
            field=models.ManyToManyField(to='basic_ui.Tool'),
        ),
    ]
