# Generated by Django 4.0.2 on 2022-06-23 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_ui', '0011_basicblockset_has_data_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discoveryranking',
            name='bbentry',
        ),
        migrations.AddField(
            model_name='basicblockset',
            name='discovery_ranking',
            field=models.ManyToManyField(through='basic_ui.DiscoveryRanking', to='basic_ui.Discovery'),
        ),
        migrations.AddField(
            model_name='discoveryranking',
            name='basicblockset',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='basic_ui.basicblockset'),
            preserve_default=False,
        ),
    ]
