# Generated by Django 4.0.2 on 2022-06-23 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_ui', '0012_remove_discoveryranking_bbentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicBlockSetMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bbs_interesting', models.IntegerField()),
                ('percent_bbs_interesting', models.FloatField()),
                ('num_interesting_bbs_covered', models.IntegerField()),
                ('percent_interesting_bbs_covered', models.FloatField()),
                ('num_interesting_bbs_covered_top10', models.IntegerField()),
                ('percent_interesting_bbs_covered_top10', models.FloatField()),
                ('bbset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_ui.basicblockset')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_ui.campaign')),
            ],
        ),
    ]
