# Generated by Django 4.0.2 on 2022-06-24 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_ui', '0013_basicblocksetmetrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicblockset',
            name='discovery_ranking',
        ),
        migrations.DeleteModel(
            name='DiscoveryRanking',
        ),
    ]
