# Generated by Django 4.0.2 on 2022-06-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_ui', '0014_remove_basicblockset_discovery_ranking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicblockentry',
            name='covered_by',
        ),
    ]
