# Generated by Django 3.2.6 on 2021-08-13 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_dict', models.JSONField()),
                ('termination_condition', models.JSONField()),
                ('date', models.DateField()),
                ('host_pc', models.CharField(max_length=255)),
                ('total_seconds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Discovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=63)),
                ('absblock', models.JSONField()),
                ('interestingness', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='InsnScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discovery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basic_ui.discovery')),
            ],
        ),
        migrations.CreateModel(
            name='DiscoveryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_ui.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='discovery',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_ui.discoverybatch'),
        ),
        migrations.AddField(
            model_name='discovery',
            name='occuring_insnschemes',
            field=models.ManyToManyField(to='basic_ui.InsnScheme'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tools',
            field=models.ManyToManyField(to='basic_ui.Tool'),
        ),
    ]
