# Generated by Django 3.2.6 on 2021-09-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovery',
            name='num_insns',
            field=models.IntegerField(default=42),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discovery',
            name='witness_len',
            field=models.IntegerField(default=42),
            preserve_default=False,
        ),
    ]
