# Generated by Django 3.2.6 on 2021-09-17 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_ui', '0003_auto_20210917_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovery',
            name='ab_coverage',
            field=models.FloatField(default=42),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interestingness', models.FloatField()),
                ('discovery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_ui.discovery')),
            ],
        ),
    ]
