# Generated by Django 3.2.6 on 2021-09-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_ui', '0004_auto_20210917_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoverybatch',
            name='batch_time',
            field=models.IntegerField(default=42),
            preserve_default=False,
        ),
    ]
