# Generated by Django 3.2.6 on 2021-09-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_ui', '0005_discoverybatch_batch_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoverybatch',
            name='batch_index',
            field=models.IntegerField(default=42),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='discoverybatch',
            index=models.Index(fields=['batch_index', 'campaign'], name='basic_ui_di_batch_i_95a43f_idx'),
        ),
    ]
