# Generated by Django 3.2.6 on 2021-09-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_ui', '0006_auto_20210922_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discovery',
            old_name='occuring_insnschemes',
            new_name='occurring_insnschemes',
        ),
    ]
