# Generated by Django 3.2.6 on 2021-09-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_ui', '0007_rename_occuring_insnschemes_discovery_occurring_insnschemes'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovery',
            name='generality',
            field=models.IntegerField(default=42),
            preserve_default=False,
        ),
    ]
